import type { RestoredArticleData } from "./restored-article";

const image = (slug: string, number: number, caption: string, alt = caption) => ({
  file: `/articles/${slug}/source-${String(number).padStart(3, "0")}.jpg`,
  caption,
  alt,
});

export const batchOneArticles: Record<string, RestoredArticleData> = {
  "alles-in-huis-is-scheef": {
    code: "23.2",
    title: "Alles in huis is scheef",
    deck: "Praktische afwegingen bij kromme muren, verzakte vloeren en niet-haakse aansluitingen in een oud Frans huis.",
    sourceUrl: "https://drive.google.com/file/d/1izxk8owTR_0mo9EHWElamXh4eEpLcnf7/view?usp=drivesdk",
    images: [],
    paragraphs: [
      "Vaak heb ik de uitroep gehoord: alles is scheef, veel dingen zijn krom! Hoe maak ik dat recht en haaks?",
      "Mijn aannemer zei: Dans une maison traditionelle rien n’est ni droit ni equerre, ni aplomb ni au niveau. Dus, in een oud huis is bijna niets recht en haaks, waterpas of verticaal.",
      "Maar hoe te handelen als u in een oud huis iets wilt verbouwen of iets nieuws wilt installeren?",
      "Een optie is: alles wat u nieuw aanlegt waterpas en verticaal aanleggen. U kunt toch niet hier een naar rechts scheef staande muur volgen en daar een deurpost die naar links scheef staat, want alles wat krom is wilt u toch in de loop der jaren vervangen. Helaas is dat niet overal mogelijk. En zolang niet alle scheve constructie-elementen vervangen zijn benadrukken de nieuwe exact verticale en horizontale componenten juist dat er iets scheef loopt. Dus dan toch beter een iets scheve vloer of muur als referentie nemen?",
      "Roger Fischer zegt zelfs in zijn boek L'art de restaurer une maison paysanne: Les lignes droites déshumanisent une maison. Tous qui est trop rectiligne doit être évité. Na ja, zo ver wil ik niet gaan.",
      "Het volgende statement kan ik eerder accepteren: Een beetje scheef, dat maakt toch juist het karakter van een oud huis uit.",
      "Maar soms zijn er ook technische problemen die door de kromme muren of vloeren ontstaan. Deuren met een scheef kozijn vallen steeds vanzelf open of dicht, en klemmen vaak of hebben tochtkieren. Dan kan men de deuren voorzichtig bijwerken zodat zij net zo krom zijn als het kozijn. Bij kasten die op een niet horizontale vloer staan (en waarvan de oneffenheden door stelpoten alleen onvolkomen gecompenseerd kunnen worden) zijn de deuren niet normaal te openen en te sluiten – zij klemmen steeds. Een oplossing hiervoor is een console die de scheve vloer compenseert en op wiens recht en horizontaal oppervlak de kast komt te staan. Helaas wordt hierdoor de doorgezakte vloer, die anders niet zou zijn opgevallen, nog eens benadrukt.",
      "Een vloer met 'afloop' kan uiterst hinderlijk zijn, en ik zou die bij een renovatie horizontaal en recht maken. Zie hierover menupunt 08.1.4. Bij een plafond is dat niet erg, maar als men dichtbij een doorgezakt plafond een recht element aanbrengt dan wordt het scheve en doorgezakte juist weer benadrukt. Dus zou ik het plafond even laten zoals het is.",
      "Als u een niet haakse muur of vloer wilt betegelen komt dat op lelijk snijwerk neer (wat ook weer het scheve benadrukt). Als u de scheve muur eerst recht maakt, bijvoorbeeld door een voorzetwand van gipsplaten, dan kunt u een voor het betegelen geschikte geometrie scheppen. Voor het betegelen van een vloer tussen scheve muren zie de oplossingen onder 16.4. Als u een nieuwe muur of voorzetwand aan een scheve muur aan wilt laten sluiten dan kan dat met een paar trucs, zie 23.6.",
    ],
  },
  "betegelen-van-oude-vloeren": {
    code: "08.1.8",
    title: "Betegelen van een oude plankenvloer",
    deck: "Een oude, ongelijke houten vloer verstevigen en vlak maken als ondergrond voor tegels.",
    sourceUrl: "https://drive.google.com/file/d/1RUm0Xz58FdJZpvwNgw8noxhdgq8hNpms/view?usp=drivesdk",
    images: [
      image("betegelen-van-oude-vloeren", 0, "Afb. 08.1.8-1 · Oude vloer met getordeerde balken op verschillende hoogtes"),
      image("betegelen-van-oude-vloeren", 1, "Afb. 08.1.8-2 · Verzaagde vloerplanken tussen de balken met multiplex afdekking"),
    ],
    paragraphs: [
      "Wanneer men een oude plankenvloer wil betegelen, bijvoorbeeld om daar een badkamer te creëren, dan moet de vloer zo stijf en recht als mogelijk zijn.",
      "Als de vloer verend is dan is het goed de onder 8.1.2 genoemde adviezen te volgen. Dan kan men erover nadenken welk soort vloer men op deze balken wil leggen. Een mogelijkheid is een vloer met Lewisplaten te leggen, zie 8.2.3. Maar het kan ook met een verstevigde oude plankenvloer.",
      "Verondersteld de vloer ziet er uit als op afb. 1.",
      "## Analyse",
      "De balken liggen niet op dezelfde hoogte, enkele balken zijn getordeerd.",
      "## Acties",
      "Men kan de oude planken verzagen en tussen de balken op hulplatjes (1) plaatsen, zie afb. 2. Met touwtjes en/of een rei zorgt men ervoor dat alle planken op de juiste hoogte komen; de verzaagde planken moeten precies op één hoogte komen te liggen en zeker zo hoog als de hoogste balk. Op erg diep liggende balken kan men vullatjes (3) plaatsen.",
      "Als de multiplexplaat (4) om de 200mm met deze planken verschroefd wordt is 10mm multiplex voldoende. Op die manier komt de nieuwe vloer niet meer dan 0 à 5mm hoger te liggen dan de vroegere vloer:",
      "10mm multiplex + 5mm lijm + 10mm tegels → 25mm, planken waren 22mm.",
      "10mm multiplex + 4mm lijm + 8mm tegels → 22mm, planken waren 20 of 22mm.",
      "Hoogteverschillen en getordeerde balken zijn hier overdreven getekend om het principe duidelijk te maken.",
      "Voor een tegelvloer op Lewisplaten zie 8.2.3.",
    ],
  },
  "condensproblemen-bij-dakramen": {
    code: "06.5.6",
    title: "Condensproblemen bij dakramen",
    deck: "Waarom condens juist bij dakramen ontstaat en waarom vrije luchtcirculatie rond het raam belangrijk is.",
    sourceUrl: "https://drive.google.com/file/d/1xEOYX1RwYoH8Nt1YTCfUw0AyyhXXadra/view?usp=drivesdk",
    images: [
      image("condensproblemen-bij-dakramen", 0, "Afb. 06.5.6-1 · Dakraam met radiator en open binnenafwerking"),
      image("condensproblemen-bij-dakramen", 1, "Afb. 06.5.5-2 · Binnenafwerking met mogelijke zone voor stilstaande lucht"),
    ],
    paragraphs: [
      "Ramen vormen in de omsluitende constructies van een vertrek steeds de koudste plek. En omdat condensatie van luchtvocht juist op de koudste plek plaatsvindt heb je, als er condensvorming optreedt, deze op de ramen. Wilde men dit voorkomen, dan had men de warmteweerstand van de ramen net zo groot moeten maken als die van de aanpalende muren of dakvlakken; dat is alleen met een groot aantal achter elkaar liggende isolatieruiten mogelijk, in de praktijk dus uitgesloten.",
      "Bij dakramen is dit door hun plaatsing in het schuine dak nog iets kritischer, want deze koelen meer af dan verticale ramen, vooral als zij blootgesteld zijn aan regen, hagel en sneeuw. Daarbij komt dat zij door hun schuine plaatsing aan de binnenkant meer dan een verticaal raam blootgesteld zijn aan opstijgende warme vochtige lucht.",
      "Hieruit moge duidelijk zijn dat aan de binnenkant van dakramen steeds een vrije luchtcirculatie gewaarborgd moet zijn. Stagnerende lucht in een nis onder een dakraam is uit den boze, zie de voorbeelden onder 06.5.2, afb. 10-13. Niet voor niets zijn de door de fabrikanten aangeboden binnenafwerkingen wijd geopend, niet alleen voor een betere lichtval, maar juist voor een goede beluchting van de ruimte voor/onder het raam.",
      "Een onder het dakraam geplaatste radiator is bijzonder nuttig, zie afbeelding 1 hieronder en afb. 2 in 06.5.5.",
      "Bij het dakraam op afbeelding 2 heb ik de indruk dat aan de buitenkant van de mooie geprefabriceerde afwerking toch een tegengestelde helling naar het kozijn toe aansluit, zie de pijl, dus een plaats waar lucht blijft staan en condensatie op kan treden. De onderkant van de afwerking had ook een beetje meer verticaal kunnen staan, waarom niet in een vlak met de muur daaronder?",
    ],
  },
  dakbuitenisolatie: {
    code: "15.4.1",
    title: "Dakbuitenisolatie",
    deck: "Een korte historische introductie op buitenisolatie van een hellend dak, vaak aangeduid als sarking.",
    sourceUrl: "https://drive.google.com/file/d/1O3jzdfZWsyfH3tsGVZcd2rNkywo-X6Lw/view?usp=drivesdk",
    images: [
      image("dakbuitenisolatie", 0, "Afb. 15.4.1-1 · Historisch sarkingelement van Isotec"),
      image("dakbuitenisolatie", 1, "Afb. 15.4.1-2 · Geïntegreerde panlat van het sarkingelement"),
    ],
    paragraphs: [
      "Bij zolderisolatie heeft men de keuze tussen buitenisolatie, bijv. door sandwichplaten of isolatie op de sporen, en binnenisolatie, wil zeggen tussen of onder de sporen. Buitenisolatie is alleen bij een complete dakrenovatie te doen, waarbij de pannen, panlatten etc. verwijderd worden. Bij een dak in redelijke toestand wordt daarom eerder binnenisolatie toegepast; die wordt onder 15.5 beschreven.",
      "## Buitenisolatie",
      "Voor buitenisolatie, vaak sarking genoemd, bestaan platen die een binnen- en buitenafwerking hebben en waarin vaak ook de panlat geïntegreerd is. Zie bijvoorbeeld ISOTEC.",
      "Een goed voorbeeld voor een binnenisolatie van een zolder waarbij de chevrons geheel en de gordingen gedeeltelijk verdwijnen is op deze Isover video te zien. Hier een ander voorbeeld.",
      "Een andere video laat zien hoe men binnen- en buitenisolatie (tussen chevrons en op de chevrons) kombineert.",
      "https://www.youtube.com/watch?v=u31Pz2-FlLQ",
    ],
  },
  "gaten-in-hout-opvullen": {
    code: "23.5",
    title: "Gaten in hout opvullen",
    deck: "Uitgevallen knoesten en oude beslaggaten gecontroleerd uitboren en vullen met passende houten plaatjes.",
    sourceUrl: "https://drive.google.com/file/d/1JTQneHH68o5VI7m6E92y4O2x8_ZB31eL/view?usp=drivesdk",
    images: [
      image("gaten-in-hout-opvullen", 0, "Afb. 23.5-1 · Eerste boormal met Forstnerboor en vulplaatjes"),
      image("gaten-in-hout-opvullen", 1, "Afb. 23.5-2 · Boormal op een deur vastgeklemd"),
      image("gaten-in-hout-opvullen", 2, "Afb. 23.5-3 · Nieuwe boormal van 16 mm MDF"),
      image("gaten-in-hout-opvullen", 3, "Afb. 23.5-4 · Forstnerboor"),
    ],
    paragraphs: [
      "Hout heeft kwasten, of zegt men knoesten? Die kunnen storend zijn of juist decoratief. En vaak vallen de knoesten uit het hout als dit door drogen of vochtopname krimpt en uitzet. De ontstane gaten in vloeren, deuren etc. kan men dan uitboren en met houtplaatjes opvullen. Deze plaatjes, die met het juiste verloop van de nerf ingezet moeten worden, zijn in diameters van 10 tot 40 of 50mm verkrijgbaar, oplopend per 5mm.",
      "Maar hoe het gat uitboren? De boor heeft geen plek om zijn punt te centreren, omdat die juist weggevallen is. Vrijhand boren leidt dan steeds tot lelijke gerafelde gaten waarin geen plaatje een houvast vindt. Dan helpt het volgende:",
      "Men boort in plaatmateriaal, bijv. multiplex of MDF van minimaal 8mm, met de gekozen boor een gat. Deze boren heten overigens Forstnerboor, en die worden soms ook aangeduid als komscharnierfrees, omdat die voor het inboren van de typische keukenkastscharnieren gebruikt worden. Dan legt men dit hout-met-gat op het uit te boren gat in de vloer of deur, klemt het met een lijmtang vast of gaat met de voet erop staan, en heeft voldoende geleiding voor de boor. Ik heb in mijn werkplaats een plaat met alle normaliter voorkomende gaten.",
      "Ook als er in deuren gaten van vroegere sloten zijn kan men die op deze manier uitboren en opvullen.",
      "## Nog een beetje achtergrondinformatie",
      "Dit gereedschap heet Forstnerboor naar zijn uitvinder Benjamin Forstner, die hem rond 1870 uitgevonden heeft; eigenlijk is het meer een frees dan een boor. Normaal dient men een Forstnerboor steeds in een boorstandaard (of stationaire werkbankboormachine, engl. drill press) te gebruiken, en dat wordt bij het inboren van keukenkastscharnieren ook gedaan; het gebruik in een handboormachine leidt meestal tot onbevredigende resultaten, maar het hierboven beschreven boorplaatje is een goede hulp.",
    ],
  },
  "deuren-opknappen": {
    code: "09.1",
    title: "Deuren opknappen",
    deck: "Waarom oude deuren vaak het herstellen waard zijn en welke aanpak Christian voor zijn eigen huis koos.",
    sourceUrl: "https://drive.google.com/file/d/1jW-YVDVh-LO4I4mCRd0HGao9MeV8R_9a/view?usp=drivesdk",
    images: [
      image("deuren-opknappen", 0, "Verzamelplaats met afgedankte oude deuren"),
      image("deuren-opknappen", 1, "Oude deuren en kozijnen die mogelijk nog hersteld kunnen worden"),
    ],
    paragraphs: [
      "### Deuren, ramen en hun sloten/scharnieren opknappen",
      "U kunt natuurlijk alle oude deuren door nieuwe uit de bouwmarkt vervangen. Ze bestaan er als bloc-porte plane, als postformé, classic en sapin en natuurlijk ook en chêne.",
      "En de oude komen dan hier terecht, op de verzamelplaats voor oude deuren, gefotografeerd op het terrein van een bedrijf dat kunststof deuren en ramen plaatst. Jammer, velen lijken nog het opknappen waard! Hoe? Dat leest u in hoofdstuk 9.1.1 en 9.1.2.",
      "Maar de baas van dit bedrijf vertelde mij dat hij sommige oude deuren en ramen heel goed kan verkopen, soms verdient hij hieraan meer dan aan de nieuwe.",
      "Ik heb het anders gedaan; ik heb de oude deuren waar het kon op hun plaats gelaten, weer sluitend gemaakt, het hang- en sluitwerk gereviseerd, of waar nodig nieuw hang- en sluitwerk in de oude stijl geplaatst.",
      "Wilt u dat ook?",
      "Ik laat u zien hoe dat met de middelen die een klusser ter beschikking heeft mogelijk is.",
    ],
  },
  "keuze-van-een-raam": {
    code: "06.5.1",
    title: "Keuze van plaats, grootte en model raam",
    deck: "Historische vuistregels voor lichtoppervlak, plaatsingshoogte en de keuze van een dakraam.",
    sourceUrl: "https://drive.google.com/file/d/1BEmLcAcSDm_Nvx-JWYgWoJf7JLOhqgyQ/view?usp=drivesdk",
    images: [],
    paragraphs: [
      "U dient de volgende vragen te onderzoeken:",
      "Hoeveel raamoppervlak?",
      "Wat is de goede plaats?",
      "Welke afmetingen en welk model raam?",
      "Voor de plaatsing ten opzichte van andere gevelelementen (ramen, deuren) zie de regels in hoofdstuk 3 van het menupunt 06.4 over dakkapellen.",
      "Het benodigde raamoppervlak hangt van een aantal factoren af. Wilt u een lichte leefruimte? Wilt u zicht op het landschap? Of gaat het alleen om een beetje licht voor een zolderkamer?",
      "Een goed richtgetal is de 10%-regel: het totale raamoppervlak dient 10% van het vloeroppervlak te bedragen als u een ‘normale’ verlichting wilt. Voor een woonruimte is 12 à 15% beter, voor een rommelzolder kunt u het ook met minder doen. En het liefst zou ik bijzonder grote dakramen alleen op het noorden plaatsen; niet voor niets hebben alle schildersateliers grote ramen op het noorden.",
      "Voor de ideale hoogte van dakramen gelden twee regels:",
      "Houd het hart van het venster ongeveer op ooghoogte, dus 160 à 180cm.",
      "De onderkant van het venster kan men het beste 90 à 120 cm boven de vloer plaatsen.",
      "Zie hiervoor hoofdstuk 6.5.2, afb. 7-9. Natuurlijk is dat, vooral bij traditionele huizen, lang niet altijd realiseerbaar.",
      "Voor bepaalde modellen, vooral uitzetvensters die alleen bij dakhellingen tussen 15 en 55° gebruikt kunnen worden, is het belangrijk de helling van uw dak na te meten.",
      "Een aantal andere keuzecriteria zijn in hoofdstuk 06.5.7 vermeldt. Voor het bepalen van de maten van het dakraam moet u uw dakconstructie kennen. Hier bestaan principieel twee moeilijkheden die in de hoofdstukken 06.5.2 en .3 nader toegelicht worden:",
      "In nieuwere huizen zijn isolatie en dakbalken onzichtbaar weggewerkt. Dus voordat u een gat voor een dakraam maakt, moet u nauwkeurig bepalen waar de balken (gordingen en sporen, les pannes et les chevrons) lopen.",
      "Bij traditionele daken boven onbewoonde zolders (combles non amenagées) daarentegen is de balkconstructie meestal duidelijk te zien, maar de onregelmatigheid ervan kan de plaatsing van ramen moeilijk maken.",
      "Ik geef daarom twee verschillende benaderingen, een voor moderne daken (6.5.2) en een voor traditionele (6.5.3).",
    ],
  },
  "krakende-vloeren": {
    code: "08.1.7",
    title: "Krakende vloeren",
    deck: "De bron van kraak- en piepgeluiden opsporen en beoordelen of vastzetten, opvullen of vervanging nodig is.",
    sourceUrl: "https://drive.google.com/file/d/13ZmhTG1HSntqHTVNfr8TQCtfS9hl_y5p/view?usp=drivesdk",
    images: [
      image("krakende-vloeren", 0, "Afb. 08.1.7-1 · Vloer van onderen met een te hoog liggende plank en een wig"),
      image("krakende-vloeren", 1, "Afb. 08.1.7-2 · Pijpbeugel met geluiddempende inlage"),
    ],
    paragraphs: [
      "In oude huizen vindt men vaak plankenvloeren die kraken. In bepaalde culturen werden krakende vloeren zelfs bewust toegepast; zo kon men horen als iemand in huis loopt, of via het couloir naar de kamer van de heer komt.",
      "## Hoe ontstaat het kraken van vloeren?",
      "Houten vloeren kraken (ik ben nog geen krakende betonvloer tegengekomen) als de constructieonderdelen ten opzichte van elkaar bewegen. Natuurlijk beweegt elke houten vloer een beetje als men eroverheen loopt. Hoe veel hangt af van de stijfheid van de vloer. Als alles gelijkmatig meebeweegt hoort men geen kraken. Pas als de onderdelen (balken en planken) niet dezelfde beweging maken hoor je geluiden. De geluiden kunnen ontstaan als planken onderling bewegen, planken ten opzichte van de balken bewegen, of balken die aan elkaar bevestigd zijn onderling bewegen. Het is dus belangrijk dat alle vloerplanken en balken vast op elkaar zitten.",
      "Op constructies, die vooral in Nederland voorkomen, zoals OSB op balken en daarop dunne planken of klik-klak-parket, ga ik in dit stuk niet in; ik beperk me tot de in oude Franse huizen gebruikelijke simpele vloeren met planken op balken.",
      "Soms hoort men, niet alleen in huisvrouwenbladen, adviezen zoals: strooi talkpoeder in de kieren van de vloer, smeer meubelwas of vloeibare zeep in de spleten, of gebruik hiervoor grafietpoeder.",
      "Dat helpt soms voor een poosje, maar meestal niet, en op den duur helemaal niet, want de planken blijven bewegen, alleen een poosje met minder geluid. De enige echte remedie is het onderlinge werken van de constructie-elementen te elimineren.",
      "## De eerste actie: vaststellen waar het kraken vandaan komt",
      "Men dient van de onderkant (en als dat niet kan van de bovenkant) vast te stellen op welke plek het kraakgeluid ontstaat. Als de vloer van onder toegankelijk is laat men iemand op de vloer lopen, systematisch van rechts naar links, en baan naast baan. Dan kan degene die de vloer aan de onderkant observeert horen (en soms ook zien) op welke plek het gekraak ontstaat. Die plek moet men dan onder handen nemen.",
      "Als het om een plank gaat die bij de balkoplage ten opzichte van zijn buurmannen beweegt, dan bestaan er twee mogelijkheden: deze plank van boven stevig op de balk vastschroeven, of tussen deze plank en de balk een wig of stukjes multiplex inslaan.",
      "Welke van deze twee mogelijkheden de voorkeur verdient hangt af van de plaats die de plank in ruste inneemt. Ligt de bovenkant van de plank hoger dan de andere, dan is vastschroeven de oplossing; ligt zij op dezelfde hoogte dan moet men de ruimte eronder opvullen.",
      "Vloerdelen kunnen ook in de breedte gekrompen zijn. Dan zitten messing en groef gedeeltelijk of geheel uit elkaar. Bij gedeeltelijk uitgeschoven messing kan deze makkelijk breken, en dan bewegen de planken tegen elkaar, net zo als bij compleet uitgeschoven messing en groef. Deze situatie ontstaat als de planken, die misschien met een hoog vochtgehalte gelegd zijn, later gekrompen zijn. Een messing kan ook gebroken zijn als planken op balken met een te grote HOH-afstand gelegd zijn.",
      "Als dit uw situatie is, dus als de planken onderling bewegen omdat messing en groef versleten of afgebroken zijn (meestal is de messing afgebroken) dan is hieraan niets te doen. Die vloer moet gewoon vervangen worden. Alleen nieuwe correct gelegde vloerplanken, en bij voorkeur ook extra balken die de vrije overspanning verkleinen, maken in dit geval een einde aan het gekraak.",
      "Wanneer er ingewikkelde balkconstructies liggen, bijvoorbeeld een uitwisseling of andere constructies waar de ene balk door de andere gedragen wordt, dan is het vaak zo dat de kleinere balken ten opzichte van de grote doorlopende balken bewegen. Ook hier is het mogelijk deze bewegingen door het inslaan van wiggen of stukjes multiplex uit te bannen. Soms is het ook doelmatig een grote schroef (tirefonds) door de balkverbinding te schroeven of een ijzeren balkverbinder te plaatsen.",
      "Als het meer een piepend geluid is dan komt dat van de spijkers waarmee de planken op de balken bevestigd zijn. Als die los zijn dan glijdt de plank bij belasting over de spijker naar beneden (en bij het wegvallen van de belasting weer naar boven) en veroorzaakt het piepend geluid. Dan slaat men de spijker met een drevel diep in, en ernaast nog twee schuine spijkers, of men draait ernaast een schroef in. Dan zit de plank hopelijk op de balk vast.",
      "Behalve deze geluiden uit de balk- en plankconstructie komt het ook nog voor dat niet de vloer zelf kraakt maar leidingen die onder de vloer lopen en daaraan zijn opgehangen. Vooral CV- en warmwaterleidingen kunnen lastig zijn, omdat die meer uitzetten en krimpen dan andere leidingen. Dan helpt alleen: alle doorvoeringen door balken ruim uitboren en de leidingen vrij zwevend ophangen, en natuurlijk leidingbeugels, buisklemmen of zadels met rubberen voeringen toepassen. Deze worden aangeboden als pijpbeugels met inlage, afb. 2.",
      "En verder mag iedere leiding (tenminste die waarvan een thermische uitzetting verwacht kan worden) maar op één punt gefixeerd zijn, alles andere moeten schuivende of anderszins bewegende ophangingen zijn.",
      "## Ik wil nog een observatie vermelden",
      "Vaak heeft men last van gekraak als men een zolder bewoonbaar maakt. De zolder was misschien alleen voor de opslag van hooi bedoeld, en zijn vloerconstructie was hierop aangepast. Daarvoor was een grote HOH-balkafstand van misschien 1,2m voldoende, en dunne planken van 21mm. Maar als u dat met de huidige maatvoering vergelijkt, balken met 60 of 75cm HOH en planken van 23 of 25mm, dan begrijpt u dat de oude vloer gewoon moet kraken, en dat messingen (als die er zijn) bij de grote vrij dragende lengte overbelast zijn en breken. Het is daarom aan te bevelen, voor men een zolder bewoonbaar maakt, de vloerconstructie aan te passen.",
    ],
  },
  "uitgezakte-luiken": {
    code: "09.4.4",
    title: "Uitgezakte luiken weer in vorm brengen",
    deck: "Het verhaal van Kees, Piet en François — en hoe een oude timmerman uitgezakte luiken weer recht en haaks stelt.",
    sourceUrl: "https://drive.google.com/file/d/1d6hLnGzBEkMBiCBRclwYf7_blE2HdQ6l/view?usp=drivesdk",
    images: [
      image("uitgezakte-luiken", 0, "Bovenkant van een uitgezakt traditioneel luik"),
      image("uitgezakte-luiken", 1, "Uitgezakt luik waarbij de diagonale écharpes ontbreken"),
    ],
    paragraphs: [
      "## Het verhaal van Kees, Piet en François",
      "Het Franse boerenhuisje van Kees had uitgezakte luiken. Het ging om het type eenvoudige luiken die uit planken met messing en groef samengesteld zijn, en met daarop de drie decoratieve planken in Z-vorm, die alles bij elkaar houden, zoals op afb. 32-34 in menupunt 09.4.5. Een beetje schaven aan de sluitkant, de onderkant recht zagen, en alles moet goed zijn dacht hij. Maar omdat de luiken echt in parallellogramvorm uitgezakt waren was er ook aan de bovenkant een lelijke scheve spleet. Wat dus te doen?",
      "Zijn vriend Pietje bekeek het probleem en kwam tot de conclusie:",
      "Is het uitzakken werkelijk het probleem dan kan je gaan schaven en zagen maar dat moet dan elk jaar gebeuren. Weet je wat ik zou doen: haal het luik eraf, probeer het luik weer haaks te maken; indien mogelijk opnieuw lijmen met vullende PUR-lijm en dan ijzeren hoeken op de luiken schroeven om het geheel te fixeren. PUR = Polyurethan is een constructielijm die door bruisen kieren vult.",
      "Toen Kees juist het eerste luik op de schragen had, kwam de oude buurman François langs, en die was toevallig in zijn actieve leven timmerman geweest. Toen hij van Kees hoorde wat hij van plan was schudde hij zijn kaal hoofd en hield een college over luiken. Hij had het over de lames, de verticale planken met messing en groef en afgeschuinde kanten, en over het Z-verband, de barres et écharpes. De lames hebben een standaarddikte van 21mm, bij erg grote luiken ook 28 mm.",
      "Zij hebben vroeger die planken nooit aan elkaar gelijmd, want dat belemmert het werken van het hout, en dat gebeurd bij iedere wisseling van de luchtvochtigheid. ‘Le bois respire comme nous’ zei hij en ademde diep ter demonstratie van hetgeen hij bedoelde. Als de werking in de tong-en-groef van de lames door de verlijming belemmerd wordt, kan het hout van de lamellen scheuren. En toen liet hij Kees zien hoe hij luiken weer recht en haaks stelt.",
      "Laat de luiken op hun plaats hangen. Alle schroeven een of twee slagen losdraaien, ook de slotbouten van de hengen. Dan de luiken in gesloten toestand met wiggen of ondergelegde stukjes multiplex recht en haaks stellen. De schroeven weer vastdraaien.",
      "Dan kijken of de écharpe goed zit. Die is het belangrijkst! Dit diagonaalverband van de Z-vormige latten (barres et écharpes) houdt het luik in vorm en voorkomt uitzakken. De écharpe moet strak tussen de horizontale barres zitten. Zonodig een stukje hout erbij leggen of een nieuwe strak zittende écharpe maken. De standaardmaat hiervoor is 70x22 mm, en met eenzijdige afschuining.",
      "Overigens: indien het weer recht en haaks gezette luik niet goed sluit, dan moet er geschaafd en/of gezaagd worden. En wél zo zagen dat de onderkant van de luiken minimaal 5mm (beter 10 of 12mm) boven de negge (buitenvensterbank) zit, want op deze manier is een goede afwatering gewaarborgd. Bij een strak op de negge rustend luik wordt onherroepelijk water in het hout opgezogen en dat is beslist niet goed.",
      "Kees is nu trots op zijn goed sluitende luiken met hun authentieke uitstraling, en Piet is ook overtuigd.",
      "Weer iets van François geleerd!",
    ],
  },
  "standaard-gereedschappen": {
    code: "20.1",
    title: "Mijn gereedschapskisten",
    deck: "Een eenvoudige verdeling tussen dagelijks handgereedschap en minder vaak gebruikt bijzonder gereedschap.",
    sourceUrl: "https://drive.google.com/file/d/1M4qpWSpeK3aHlkjeS6puHOXBCcuSOb3o/view?usp=drivesdk",
    images: [
      image("standaard-gereedschappen", 0, "De dagelijkse en bijzondere gereedschapskist van Christian"),
    ],
    paragraphs: [
      "## Links",
      "Mijn 'normale' dagelijkse gereedschapskist die ik overal in huis mee naar toe neem: hamers, tangen en schroevendraaiers (kruis en recht), beitels, meet- en aftekengereedschap. En inbus en andere sleutels.",
      "Als de kist zwaarder dan 10kg is moet ik de inhoud ervan herzien.",
      "## Rechts",
      "De tweede 'bijzondere' gereedschapskist met gereedschappen die ik niet zo vaak nodig heb: blikscharen, vijlen en raspen, in de la soldeerbout en soldeerbenodigdheden.",
    ],
  },
};
